spring:
  application:
    name: freelance-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/db_freelance_dev
    username: postgres
    password: sasa1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create